version: '3.6'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
  db:
    container_name: postgresql_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: eCommerceApp
    ports:
      - "5432:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"
volumes:
  db-data: