version: '3.6'

services:
  server:
    build: .
    ports:
      - "5000:5000"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: 'eCommerceApp'
    volumes:
      - "data:/var/lib/postgresql/data"
volumes:
  data:
